### ISSUE TITLE
Error on download

### ISSUE THREAD

**Issue by chrisbward** [AlpinDale/pygmalion.cpp#1]
```
Downloading file...
on-6b-q4_0.bin      100%[===================>]   3.52G  6.35MB/s    in 8m 49s  
md5sum: models/pygmalion-6b-q4_0.bin: No such file or directory
../examples/pyggy/download-pyg.sh: line 36: [: =: unary operator expected
Download complete but MD5 hash doesn't match. Please try again.
```

**Comment by AlpinDale** [comment]
I've noticed this issue as well. I'll modify the installer later, but for now you can download with:

`wget https://huggingface.co/alpindale/pygmalion-6b-ggml-4bit/resolve/main/pygmalion-6b-q4_0.bin`

**Comment by chrisbward** [comment]
I manually checked the hashsums, looked fine to me - it's just the bash script I'm sure

**Comment by AlpinDale** [comment]
> I manually checked the hashsums, looked fine to me - it's just the bash script I'm sure

The new [download script](https://github.com/AlpinDale/pygmalion.cpp/blob/main/examples/pyggy/download.sh) should work fine. I've also added all the V8 revisions to the download list.

**Comment by HRNPH** [comment]
Tested and it currently working just fine for me, I think you can close this
