### ISSUE TITLE
Need a guide for how to use this

### ISSUE THREAD

**Issue by VerifiedStoic** [AlpinDale/pygmalion.cpp#5]
I was able to follow your instructions to download and install this. But how do I use it? Do I need to re-download everything every time I want to use it? Does it only run in the Termux terminal, or is there a way to use a webui? Lots of people don't have knowledge beyond following instructions, and a quickstart guide would be super helpful. Even if you can tell me how to just access it again once I've closed out termux, I would be super super grateful.

**Comment by nonetrix** [comment]
Yeah, it would be great to know how to load json files as well you can find many on the Discord

**Comment by AlpinDale** [comment]
@VerifiedStoic As of now, this repo is heavily experimental and a WIP. The only way to run it is through a terminal emulator, as I haven't gotten around to implementing any sort of GUI for it. 

That said, adding a more comprehensive guide is a good idea. 

@nonetrix as for your question, it's not possible to load pre-made `.json` files to pygmalion.cpp yet. Once it's implemented to something like Kobold, you'll be able to do it.

**Comment by AlpinDale** [comment]
@VerifiedStoic I'm not sure if you've heard of it yet, but pygmalion.cpp is now integrated into KoboldAI. You can find it [here](https://github.com/LostRuins/koboldcpp). I'm closing this issue as the koboldcpp repo has a guide.

**Comment by VerifiedStoic** [comment]
Thanks for this. I'll give it a try to see how it goes. Thank you!
